### ISSUE TITLE
你好，woa_p.py无法运行，能否检查修复下呢

### ISSUE THREAD

**Issue by yercn** [isombyt/libMA#4]
你好，woa_p.py无法运行，能否检查修复下呢

**Comment by isombyt** [comment]
No, I can't fix anything without a bug report or log.
besides, this repo is not gonna to work anymore since SNDA has shutdown their game server years ago.
If you really need some functions written in woa_p.py, that just a standard implement of 3DES. Use PyCryptodome instead.
